### PR TITLE
Added Pravetz 16 support

### PR DESCRIPTION
**Pull request by elvis-epx**
This patch adds support to Pravetz 16 keyboard, which is a XT layout (capable of speaking AT protocol by moving a jumper) with a couple extra keys for Cyrillic support.

### CODE REVIEW

**Comment by tmk** [comment]
Thanks for the feedback.
Really interesting, Pravetz 16 keyboard and history of the company! I like to add support for the two keys anyway, I'll look into your codes.
https://www.seekandread.com/pravetz-16-2/


Those two keys are just specific to Pravetz 16 or any of other Burgarian/Cyrillic keyboards with the keys exist?

And could you try the keyboard with XT converter to see if it works and which scan codes are used for the keys? It would be very helpful to improve XT firmware. You can use same hardware as PS/2, just flash XT converter firmware. And Use hid_listen to see debug prints.
https://github.com/tmk/tmk_keyboard/tree/master/converter/xt_usb
https://github.com/PaulStoffregen/hid_listen


Followings are just future refrences for me and others:
`CYRILLIC_LOCK`(0x85) and `CYRILLIC_SHIFT`(0x86) are marked as 'C/L Lock' and 'C/L' rescpectively on this photo of Pravetz 16 keyboard. https://i.imgur.com/zqpAMm2.jpg

https://www.seekandread.com/pravetz-16-2/
https://en.wikipedia.org/wiki/Pravetz_computers
https://en.wikipedia.org/wiki/History_of_computer_hardware_in_Bulgaria

**Comment by elvis-epx** [comment]
Hi,

> Those two keys are just specific to Pravetz 16 or any of other Burgarian/Cyrillic keyboards with the keys exist?

I don't know for sure, but I didn't find any counterpart whatsoever in USB HID docs or Code Set documents, so my current estimation is the keys are apocryphal.

> And could you try the keyboard with XT converter to see if it works and which scan codes are used for the keys? It would be very helpful to improve XT firmware. You can use same hardware as PS/2, just flash XT converter firmware. And Use hid_listen to see debug prints.

Sure, will try.

**Comment by elvis-epx** [comment]
The XT scan codes are 54h for C/L (clash with Alt-SysRq) and 55h for C/L lock (this code I could not find in any documentation). I got these with a simple Arduino, still waiting another Teensy to arrive in order to test the actual converter.

**Comment by tmk** [comment]
Great. Thanks for the XT scan codes!

**Comment by elvis-epx** [comment]
Confirmed it works perfectly with pristine xt_usb converter.

**Pull request closed without merging**
