### PR TITLE
fix not correctly showing 32u2 warning message when Endpints are more…

### PR DESCRIPTION
**Pull request by yangdigi**
… than 4.

### CODE REVIEW

**Comment by tmk** [comment]
what problem does this change fix actually?

**Comment by yangdigi** [comment]
When NKRO is disable and keyboard with 32u2 uses more than 4 endpoints, this waring messsage will not show.

**Comment by tmk** [comment]
number of endpoint can be more than 4 when NKRO is disabled? It doesn't seem to me. But I understand it should be checked even when NKRO is disabled.

and my concern is that when NKRO is disabled `NKRO_IN_EPNUM` is not defined, comparing undefined value is safe in pre-processor? I don't have good knowledge about cpp.

**Comment by tmk** [comment]
Merged and changed some code. Thanks.
https://github.com/tmk/tmk_keyboard/commit/a567fec91c0f9020cf050ae80410b891486f2ba3

**Pull request merged**
