### PR TITLE
Allow turning on LEDs while within layer.

### PR DESCRIPTION
**Pull request by jonhiggs**
First up, let me state that I'm not much of a C programmer so I've done anything stupid let me know and I'll fix it up.

This PR will allow you to turn on an LED while a layer is active. I found that tapping was difficult to use without an indicator.

To use it, you need to add something like this into your `led.c` file.

``` c
void led_layer_set(uint32_t state) {
    DDRD |= (1<<5);
    dprint("Set LEDs for layer change\n");

    /* Led for Layer 2 */
    if ((1<<2 & state) != 0) {
        dprint("Layer 2: on\n");
        PORTD |= (1<<5);
    } else {
        dprint("Layer 2: off\n");
        PORTD &= ~(1<<5);
    }
}
```

Cheers.

### CODE REVIEW

**Comment by tmk** [comment]
Your code seems to be fine.
I have also had some ideas to improve LED API at issue #174, your change is viable option.

Thank you.

**Comment by mrlinuxfish** [comment]
I tried using this code with an extended keymap (from Jack Humbert's planck keyboard firmware) and the code does not seem to work there. Is there any code required for common/led.h or does led.c need to be included in the keymap?

**Comment by jonhiggs** [comment]
I just took a look and there has been a big refactor to move all the core stuff into tmk_core. I've fixed it up and it should apply cleanly to the tip of master again.

Give it another go and let me know if it works better now.

**Comment by mrlinuxfish** [comment]
That works perfect, thanks so much.

**Comment by jonhiggs** [comment]
No worries. Hopefully it'll get merged into core soon so it won't fall out of sync again. ;)

Btw, thanks heaps @tmk for breaking apart the core and the keyboards. I've been looking forward to #173 getting resolved.

**Comment by Eric-L-T** [comment]
This is supported in QMK by default. Take a look at the default Ergodox EZ keymap.

**Comment by tmk** [comment]
I think this can be replaced with #304 `hook_layer_change()`.

**Pull request closed without merging**
