### PR TITLE
make NKRO default when NKRO_ENABLE #100

### PR DESCRIPTION
**Pull request by agodinhost**
keyconf bit defaults.

### CODE REVIEW

**Comment by agodinhost** [comment]
I didn't changed much - just the Makefile.lufa, eeconfig.h, eeconfig.c and the command.c.
I think it's okay but would be better to have a fast review.
ty

**Comment by tmk** [comment]
Thanks for your contribution.

About making NKRO default I'm changing my mind :D
https://github.com/tmk/tmk_keyboard/issues/100#issuecomment-70437911

**Comment by Schemetrical** [comment]
@tmk if we were to enable it ourselves how would we go about doing so?

**Comment by tmk** [comment]
I'm not sure what  you are asking.
can you elaborate your question  ?

**Comment by Schemetrical** [comment]
NKRO is now disabled by default. What if we wanted it to be enabled by default? I've checked out the PRs and NKRO_ENABLE_DEFAULT doesn't appear to be used anywhere so it does nothing.

**Comment by tmk** [comment]
this pr was not merged. you can't find it in this repository.
you have to merge into your repo first,I think.

**Comment by Schemetrical** [comment]
Oh i was mistaken, i see how its used in this pr.

**Pull request closed without merging**
