### PR TITLE
Hooks

### PR DESCRIPTION
**Pull request by njbair**
Since I'm really eager to see the new hooks API make it into the master branch (#304), I've gone ahead and rolled up all the tmk_core/newapi commits from @flabbergast and @tmk, with a few changes:

- Changed hook naming to prefixed format (`hook_*`).
- Adjusted some hook names to be more descriptive. Here's the full list:
    - `hook_init_early()`
    - `hook_init_late()`
    - `hook_usb_suspend()`
    - `hook_usb_wakeup()`
    - `hook_scan_loop()`
    - `hook_suspend_loop()`
    - `hook_bootmagic()`
    - `hook_matrix_change()`
    - `hook_layer_state_change()`
    - `hook_default_layer_state_change()`
    - `hook_led_update()`
    - ~~`hook_interval_1ms()`~~
    - ~~`hook_interval_10ms()`~~
    - ~~`hook_interval_100ms()`~~
    - ~~`hook_interval_1000ms()`~~
- Added a new hook, `hook_default_layer_state_change()`, in case the user wants to do something special for the default layer. I believe that a default layer state change will still trigger the `layer_state_change()` hook. We may want to suppress this behavior, in which case the user can always call `hook_layer_state_change()` from within the default layer hook function if that's the behavior they want.
- ~~Added time interval-based hooks for 1 millisecond, 10ms, 100ms, and 1000ms (1 second). These are based on `timer_read()` and `timer_elapsed()`, so they should be architecture-independent.~~

Everything compiles fine, although I haven't fully tested all the hooks yet in an actual project, other than `hook_init_late()` ~~and the `hook_interval_*` functions~~, which work like a charm.

### CODE REVIEW

**Comment by fredizzimo** [comment]
Also please note this pull request https://github.com/tmk/tmk_core/pull/9

Without that hook I can't implement the serial connect for Infinity Ergodox, as done here https://github.com/fredizzimo/infinity_ergodox/blob/master/user_hooks.c, in the keyboard_connect_hook.

**Comment by njbair** [comment]
@fredizzimo a couple of changes and I think your code can merge into this PR...

- That `typedef struct _host_driver_t host_driver_t;` line doesn't look like it really belongs in *hooks.h*. Is there a more suitable place for it to go? It looks like all you need to do is `#include "host_driver.h` instead, but I'm not super familiar with struct stuff.
- You've got the hook defined for Chibios, but not LUFA. Since those are the two main protocols for the new stuff, I think it would be good to port that hook over.

If you can make these changes and send me a PR to my *hooks* branch, I'll be glad to merge it into this PR. Of course, I can't guarantee this one will be pulled either, so maybe you can just wait and see. Up to you.

**Comment by fredizzimo** [comment]
I added the forward declaration to avoid having to include the host_driver.h file, and introduce additional compile dependencies. At least I think that's the proper way to do it in c. I'm a c++ programmer myself, and in that I would just write
`struct host_driver_t;`. 

Yes, I didn't add it to the LUFA, because I have no way to test that it works. I could of course make sure it compiles, but I'm still very skeptical of writing code that I can't test.

I think I can wait until this is merged, and what @tmk has to say about my addition. Also I don't think I can send pull request to the tmk_keyboard, as the Infinity Ergodox only depends on the tmk_core. At least not without doing some subtree merges. But I will talk more about that here https://github.com/tmk/tmk_keyboard/issues/313.

**Comment by flabbergast** [comment]
I am not entirely happy with the timer hooks, because they add overhead to every firmware. Hopefully the compiler optimisation will kill those time_elapsed calls and ifs when the hooks are empty, but I'm not sure about this. Also the 1ms hook will not be accurate - the matrix_scan function (well the most commonly used ones) sometimes waits 1ms (when debouncing), sometimes it doesn't.

I thought that people who would want these can actually put exactly this kind of code into the scan loop hook and implement the timers themselves pretty much like this. I am wary of adding extra functions that can create a lot of trouble if they're used incorectly {which is true for the scan loop hook already}.

Finally, if the whole point is to get some code executed at regular short intervals (e.g. LED control or something like that), in my opinion people should use directly the hardware timers for this (or on ChibiOS they also have an option of running a separate thread).

**Comment by njbair** [comment]
@flabbergast you make some good points. My only thought is that not everybody using TMK has the wherewithal or experience to program for the hardware timers, especially since the APIs are different for each protocol.

As a compromise, we can pull out the timer hooks, but add an example to the docs showing how to use `timer_read()` and `timer_elapsed()` inside of `hook_keyboard_loop()` to perform a timed action...that would probably be good enough for most purposes, including LEDs.

What do you think?

**Comment by flabbergast** [comment]
Sure, examples are absolutely fine with me; it might be good to actually have some "real keyboard" example of this.

I'm not saying that hardware timers are easy to use for people who haven't played with microcontrollers, I was just trying to say that they're the "best" solution for this kind of problem in terms of accuracy and overhead. BTW there's already an example of using a hardware timer on AVR for LED breathing, in common/avr/sleep_led.c.

**Comment by fredizzimo** [comment]
Another thing to keep in mind, is that the scan loop has to be fast, in order to handle debouncing correctly. If people use timer callbacks the wrong way, by for example doing some blocking calls to support some LEDs or LCD or whatever, it can easily take several ms and therefore possibly make the debouncing not work. It's less risky with normal code that doesn't access any hardware, but even then, it's not unthinkable for some inexperienced coder to write code that takes a few ms to execute on microcontrollers.

Threads or hardware timers, when used correctly would have almost no effect on the actual scan loop.

**Comment by njbair** [comment]
@flabbergast @fredizzimo I've removed the time interval hooks and updated the docs. Take a look at the Hooks section in README.md, as I've updated it with examples, two of which use `timer_read()` and `timer_elapsed()` with minimal impact on loop execution time.

**Comment by tmk** [comment]
@njbair Thanks.
I think most of hooks are included in tmk_core/develop now. And I'll cherry-pick your documentation later.

**Comment by tmk** [comment]
Thanks,
I think I merged most of hooks to tmk_core repo.

**Pull request closed without merging**
